version: 0.3.{build}

image: Visual Studio 2022

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

configuration: Debug

build:
  publish_nuget: false

before_build:
  - dotnet restore ".\src\Synology.Api.Client.sln"

build_script:
  - dotnet build ".\src\Synology.Api.Client.sln" -p:GeneratePackageOnBuild=false

test_script:
  - dotnet test ".\src\Synology.Api.Client.Tests\Synology.Api.Client.Tests.csproj"

nuget:
  disable_publish_on_pr: true

for:
  - branches:
      only:
        - master

    configuration: Release

    build:
      publish_nuget: true

    after_build:
      - dotnet pack .\src\Synology.Api.Client\Synology.Api.Client.csproj -c Release -o .\artifacts --include-symbols -p:SymbolPackageFormat=snupkg -p:ContinuousIntegrationBuild=true -p:PublishRepositoryUrl=true

    artifacts:
      - path: artifacts\*.nupkg
      - path: artifacts\*.snupkg

    deploy:
      - provider: NuGet
        api_key:
          secure: XnCGQpOBhRsGroi0Zy6aP8vZncxkFj9zOVnucjDTql4ZHfEudDMOR0LzW0Mz34/q
        artifact: artifacts\*.*
        skip_symbols: false
